# -*- coding: utf-8 -*-
"""data_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y7MFe052MdO_XNEvuohO-WBJ4zuAq6ck
"""

import os
import json
import random
import numpy as np
import torch
from datasets import load_dataset
from utils import ensure_dir, save_image_any, blank_image
from configs import POPE_DIR, MMS_DIR, BENIGN_TEMPLATES

class Example:
    def __init__(self, image_path, question, label):
        self.image_path = image_path
        self.question   = question
        self.label      = int(label)

class MemmapDataset(torch.utils.data.Dataset):
    def __init__(self, mm_path, labels, dtype=np.float16):
        self.n = len(labels)
        self.vocab = self._infer_vocab_size(mm_path, self.n, dtype=dtype)
        self.mm = np.memmap(mm_path, dtype=dtype, mode="r", shape=(self.n, self.vocab))
        self.X  = self.mm
        self.y  = torch.from_numpy(np.asarray(labels, dtype=np.int64))

    def _infer_vocab_size(self, mm_path, n_rows, dtype):
        bytes_per = np.dtype(dtype).itemsize
        file_bytes = os.path.getsize(mm_path)
        if file_bytes % (bytes_per * n_rows) != 0:
            raise ValueError("memmap大小与行数不整除")
        return file_bytes // (bytes_per * n_rows)

    def __len__(self): return self.n
    def __getitem__(self, idx):
        x = torch.from_numpy(self.X[idx].astype(np.float32))
        y = self.y[idx]
        return x, y

def prepare_pope_data(max_n=None):
    """导出 POPE 数据"""
    print("导出POPE...")
    ensure_dir(os.path.join(POPE_DIR, "images"))
    ds_pope = load_dataset("lmms-lab/POPE", name="default", split="test")
    out_jsonl = os.path.join(POPE_DIR, "pope.jsonl")

    with open(out_jsonl, "w") as f:
        n = len(ds_pope) if max_n is None else min(max_n, len(ds_pope))
        for i in range(n):
            ex = ds_pope[i]
            img = ex["image"]
            fname = f"pope_{i:05d}.jpg"
            fpath = os.path.join(POPE_DIR, "images", fname)
            save_image_any(img, fpath)
            y = 1 if str(ex["answer"]).strip().lower()=="yes" else 0
            f.write(json.dumps({"image": fname, "question": ex["question"], "label": "yes" if y==1 else "no"})+"\n")
    return out_jsonl

def load_pope_examples(jsonl_path, coco_dir, max_n=None):
    items=[]
    with open(jsonl_path,"r") as f:
        for line in f:
            obj=json.loads(line)
            ip=os.path.join(coco_dir, obj["image"]) if obj.get("image") else None
            if ip and not os.path.exists(ip): continue
            y=1 if str(obj["label"]).strip().lower() in ("yes","1","true") else 0
            items.append(Example(ip, str(obj["question"]), y))
            if max_n and len(items)>=max_n: break
    return items