# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y7MFe052MdO_XNEvuohO-WBJ4zuAq6ck
"""

import os
import argparse
from configs import MODEL_ID, FEAT_DIR, RUN_DIR
from utils import set_seed, ensure_dir
from data_loader import prepare_pope_data  # 等
from model_core import load_model, chat_first_token_logits
from probe import train_linear_probe, make_disjoint_splits, evaluate_probe
from gating import gated_generate

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--max_pope", type=int, default=None)
    parser.add_argument("--max_mms", type=int, default=None)
    args = parser.parse_args()

    set_seed(42)
    ensure_dir(FEAT_DIR)
    ensure_dir(RUN_DIR)

    # 1. 准备数据 (Data Prep)
    # ... 调用 data_loader 中的函数导出 jsonl ...

    # 2. 加载模型
    print(f"Loading {MODEL_ID}...")
    model, processor = load_model(MODEL_ID)

    # 3. 提取特征 (Feature Extraction)
    # ... 循环调用 chat_first_token_logits 并保存为 memmap ...

    # 4. 训练探针 (Probing)
    # ... 调用 train_linear_probe ...

    # 5. 评估与绘图
    # ... 调用 evaluate_probe 和 visualization 中的函数 ...

    # 6. Gating 实验 (Task 2)
    # ... 运行 gated_generate 循环测试 ...

if __name__ == "__main__":
    main()