# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y7MFe052MdO_XNEvuohO-WBJ4zuAq6ck
"""

import os
import io
import random
import torch
import numpy as np
from PIL import Image

def ensure_dir(p):
    os.makedirs(p, exist_ok=True)
    return p

def set_seed(s=42):
    random.seed(s)
    np.random.seed(s)
    torch.manual_seed(s)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(s)

def save_image_any(val, path):
    """保存图像并返回路径，失败返回None"""
    try:
        if isinstance(val, Image.Image):
            val.save(path)
            return path
        if isinstance(val, dict) and "bytes" in val:
            Image.open(io.BytesIO(val["bytes"])).convert("RGB").save(path)
            return path
        if isinstance(val, str) and os.path.exists(val):
            Image.open(val).convert("RGB").save(path)
            return path
        # 尝试直接打开
        Image.open(val).convert("RGB").save(path)
        return path
    except:
        return None

def blank_image():
    return Image.new("RGB", (32, 32), (128, 128, 128))

def blank_img_or_open(p):
    if p and os.path.exists(p):
        try:
            return Image.open(p).convert("RGB")
        except:
            return blank_image()
    return blank_image()